# Use OpenJDK base image
FROM openjdk:17

# Set working directory
WORKDIR /app

# Copy compiled class
COPY target/backend.jar backend.jar

# Run the Java class
ENTRYPOINT [ "java", "-jar",  "backend.jar"]
