debug: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/crudusers
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: testingdivyam12@gmail.com
    password: klxfknaeooacnmqp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: password
    key-store-type: PKCS12
    key-alias: myalias
