debug: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crudusers
    username: root
    password: "7489871104@divi"  # Enclose in quotes due to special character (@)
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
