debug: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/crudusers
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: testingDivyam12@gmail.com
    password: klxfknaeooacnmqp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
